### ISSUE TITLE
Regarding collaboration

### ISSUE THREAD

**Issue by rakeshlanjewar** [edstevo/nestjs-notifications#2]
Hey dev, 

 Are you open to collaboration? 
 I think I can contribute to this package. Let's work together.

**Comment by edstevo** [comment]
Hi Rakesh, Certainly open to collaboration. I haven’t looked at this package for a little while as I’ve been on other projects, but yes it needs work! What do you have in mind? From: Rakesh Lanjewar ***@***.***>Date: Thursday, 15 July 2021 at 11:09To: edstevo/nestjs-notifications ***@***.***>Cc: Subscribed ***@***.***>Subject: [edstevo/nestjs-notifications] Regarding collaboration (#2)Hey dev,         Are you open to collaboration?          I think I can contribute to this package. Let's work together. —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rakeshlanjewar** [comment]
We can add support for official channels like mail, SMS

Also, we can push channels to separate packages.

Also we can discuss the further roadmap

**Comment by edstevo** [comment]
Yeah definitely. I have a sendgrid channel already for another project. Could just import that. Have never looked at SMS though. Would be great.

I’ve never collaborated before, unsure how to add you to the project etc.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rakeshlanjewar** [comment]
I am creating a new monorepo, let's see what I can do.

I will update you shortly.
